# Site settings
title: Research Notes
description: "Paper reading notes on deep learning and machine learning"
author: Divi Mund
email: divimund95@gmail.com
url: "https://dmund95.github.io"
baseurl: "/ResearchNotes"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing research
collections:
  papers:
    output: true
    permalink: /:collection/:path/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md

# Sass settings
sass:
  style: compressed 